events {}

http {
    server {
        listen 80;

        # API REST: solo el Servicio 1 expone HTTP.
        # Los Servicios 2 y 3 son Event Driven puros (solo hablan por RabbitMQ),
        # por eso no tienen ruta aqui.
        location /api/pagos {
            proxy_pass http://servicio-1-procesador:3001/transacciones;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            return 200 "API Gateway funcionando\n";
        }

        # Todo lo demas va al frontend (pagina estatica)
        location / {
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
        }
    }
}
