events {}

http {
    server {
        listen 80;

        location /api/pagos {
            proxy_pass http://transacciones:3001/transacciones;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/antifraude {
            proxy_pass http://antifraude:3002/antifraude;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/comprobantes {
            proxy_pass http://comprobantes:3003/comprobantes;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            return 200 "API Gateway funcionando\n";
        }
    }
}