version: '3.8'

services:
  # API Gateway (Nginx)
  api-gateway:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    #depends_on:
    #  - servicio-1-procesador

  # Message Broker (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

  # Base de Datos - Servicio 1 (Procesador)
  db-procesador:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user_proc
      POSTGRES_PASSWORD: password_proc
      POSTGRES_DB: db_procesador
    ports:
      - "5432:5432"

  # Base de Datos - Servicio 2 (Validador Antifraude)
  db-validador:
    image: postgres:15-alpine
    container_name: db_antifraude
    environment:
      POSTGRES_USER: admin_fraude
      POSTGRES_PASSWORD: password_seguro
      POSTGRES_DB: antifraude_db
    ports:
      - "5433:5432"
    volumes:
      - ./servicio-2-validador/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Base de Datos - Servicio 3 (Emisión de Comprobantes)
  db-comprobantes:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user_comp
      POSTGRES_PASSWORD: password_comp
      POSTGRES_DB: db_comprobantes
    ports:
      - "5434:5432"

  # Microservicio 2: Lógica de Validador Antifraude (Node.js)
  servicio-2-validador:
    build: ./servicio-2-validador  
    container_name: app_antifraude
    environment:
      - DB_HOST=db-validador      
      - DB_USER=admin_fraude
      - DB_PASSWORD=password_seguro
      - DB_NAME=antifraude_db
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - db-validador
      - rabbitmq