# Ruteo por nombre de dominio para PROD
# Aplicar SOLO en el namespace grupo3-prod:
#   kubectl apply -f k8s/ingress-prod.yml -n grupo3-prod
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
spec:
  rules:
    # Dominio "oficial" (requiere hosts file o resolver rules en el cliente)
    - host: prod.grupo3.uta.cl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80
    # nip.io: DNS publico comodin -> resuelve a 146.83.102.22 sin configuracion
    - host: prod.grupo3.146.83.102.22.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80
