# Servicio 1: Procesador de Transacciones (REST + Eventos)
# 2 replicas: si un pod muere, el otro sigue atendiendo (self-healing + HA)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-1-procesador
spec:
  replicas: 2
  selector:
    matchLabels:
      app: servicio-1-procesador
  template:
    metadata:
      labels:
        app: servicio-1-procesador
    spec:
      containers:
        - name: servicio-1
          # La imagen la publica GitHub Actions en el registro publico
          image: ghcr.io/crissspi/grupo-3-pasarela-de-pagos/servicio-1-procesador:latest
          ports:
            - containerPort: 3001
          env:
            - name: RABBITMQ_URL
              value: amqp://rabbitmq
            - name: DB_HOST
              value: db-svc1
            - name: DB_NAME
              value: transacciones_db
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: servicio-1-procesador   # el gateway lo alcanza por este DNS
spec:
  selector:
    app: servicio-1-procesador
  ports:
    - port: 3001
